[package]
name = "pine-syscall"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Linux and Windows syscall translation for Pine"
repository = "https://github.com/KooshaPari/Pine"
readme = "../../README.md"

[dependencies]
pine-core = { path = "../pine-core", version = "0.1.0" }
libloading = "0.8"
